name: cuml_dev
channels:
- rapidsai
- nvidia
- rapidsai-nightly
- conda-forge
dependencies:
- cudatoolkit=11.5
- rapids-build-env=22.02.*
- rapids-notebook-env=22.02.*
- rapids-doc-env=22.02.*
- cudf=22.02.*
- rmm=22.02.*
- libcumlprims=22.02.*
- dask-cudf=22.02.*
- dask-cuda=22.02.*
- ucx-py=0.24
- ucx-proc=*=gpu
- dask-ml
- doxygen>=1.8.20
- libfaiss>=1.7.0
- faiss-proc=*=cuda
- umap-learn
- scikit-learn=0.24
- treelite=2.1.0
- statsmodels
- seaborn
- hdbscan
- nltk
- pip
- pip:
    - sphinx_markdown_tables
    - git+https://github.com/dask/dask.git@2021.11.2
    - git+https://github.com/dask/distributed.git@2021.11.2
