# This is a basic workflow to help you get started with Actions

name: scan

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Pulse-Pull-Image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Docker pull
        run:  |
          docker login quay.io -u nvidia+blossom_ro -p ${{ secrets.QUAY_RO_TOKEN }}
          docker pull quay.io/nvidia/pulse:condatest
          docker images
      - name: code checkout
        uses: actions/checkout@v2
      - name: Test Pulse image
        run: |
          docker run --rm -i -v $GITHUB_WORKSPACE:/src -w /src quay.io/nvidia/pulse:condatest /bin/bash ./pulse_oss_scan.bash
          ls -l
        env:
          PULSE_API_TOKEN: ${{ secrets.BD_API_TOKEN }}
          PULSE_SCAN_PROJECT: "cuml-github-project"
          PULSE_SCAN_PROJECT_VERSION: "test"
      - name: Upload scan reports in Artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: scanReport.json
  
